---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

- block:
    - name: Including trunk repository setup
      include: "repositories/trunk.yml"
      when:
        - not stable_repositories
        - not testing_repositories
      static: no

    - name: Including stable repository setup
      include: "repositories/stable.yml"
      when:
        - stable_repositories != false
        - not testing_repositories
      static: no

    - name: Including testing repository setup
      include: "repositories/testing.yml"
      when:
        - testing_repositories != false
        - not stable_repositories
      static: no

    - name: Incompatible repository setup
      fail:
        msg: "You can't specify both testing and stable repositories."
      when:
        - testing_repositories != false
        - stable_repositories != false
  vars:
    task: "tasks/repositories.yml"
  rescue:
    - name: Failure occurred, executing rescue
      include: roles/common/tasks/rescue.yml
      static: no
