---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

- name: Update packages
  package:
    name: "*"
    state: "latest"
  retries: "3"
  delay: "20"

- name: Enable powertools repo on CentOS8
  # FIXME(jcapitao): Remove this task when CentOS 8 repoids change is included
  # in new CentOS 8 (8.3) based image [1].
  # [1] https://review.opendev.org/c/openstack/diskimage-builder/+/765963
  shell: "sudo dnf config-manager --enable powertools"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"
  changed_when: False

- name: Install base packages
  package:
    name: "{{ base_packages }}"
    state: "present"
  retries: "3"
  delay: "20"

- name: Install debug packages
  package:
    name: "{{ debug_packages }}"
    state: "present"
  retries: "3"
  delay: "20"

- name: set fact
  shell: /usr/bin/rpm -qa sysstat --queryformat %{VERSION}
  register: sysstat_version

- name: Run sysstat every minute instead of every 10 minutes (systemd)
  replace:
    dest: "/usr/lib/systemd/system/sysstat-collect.timer"
    regexp: '10'
    replace: "1"
  when: "{{ sysstat_version.stdout is version('10.3.1', '>=') }} "

- name: Run sysstat every minute instead of every 10 minutes (cron)
  replace:
    dest: "/etc/cron.d/sysstat"
    regexp: '^\*\/10.*sa1 1 1'
    replace: "* * * * * root /usr/lib64/sa/sa1 1 1"
  when: "{{ sysstat_version.stdout is version('10.3.1', '<') }} "

- name: Enable sysstat
  service:
    name: "sysstat"
    enabled: "yes"
    daemon_reload: "yes"
    state: "started"

# CentOS doesn't come provisioned with the hostname and hostname fqdn configured
# in /etc/hosts, this can be a problem for things like rabbitmq.
- name: Ensure the hostname and fqdn is configured in /etc/hosts
  lineinfile:
    dest: "/etc/hosts"
    line: "127.0.0.1 {{ ansible_hostname }} {{ ansible_fqdn }}"
    state: present
