---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

- name: Create log folder to centralize logs in
  file:
    path: "{{ log_destination }}"
    state: "directory"
    recurse: "yes"

- name: Install base packages
  yum:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ base_packages }}"
  retries: "3"
  delay: "20"

- name: Install debug packages
  yum:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ debug_packages }}"
  retries: "3"
  delay: "20"

- name: Enable sysstat
  service:
    name: "sysstat"
    enabled: "yes"
    state: "started"

- name: Run sysstat every minute instead of every 10 minutes
  replace:
    dest: "/etc/cron.d/sysstat"
    regexp: '^\*\/10.*sa1 1 1'
    replace: "* * * * * root /usr/lib64/sa/sa1 1 1"

# CentOS doesn't come provisioned with the hostname and hostname fqdn configured
# in /etc/hosts, this can be a problem for things like rabbitmq.
- name: Ensure the hostname and fqdn is configured in /etc/hosts
  lineinfile:
    dest: "/etc/hosts"
    line: "127.0.0.1 {{ ansible_hostname }} {{ ansible_fqdn }}"
    state: present

# Setup qemu-kvm nested virtualization
# This is the hypervisor used in our tests.
- name: Install qemu-kvm
  yum:
    name: "qemu-kvm"
    state: "present"
  retries: "3"
  delay: "20"

# Grab CPU flags from "/proc/cpuinfo" and put the result into the
# "cpu_flags_cmd" variable.
- name: Get cpu flags
  command: |
    awk -F: '/^flags/ {print $2; exit}' /proc/cpuinfo
  register: cpu_flags_cmd
  changed_when: false

# Extract the flags into a list variable named "cpu_flags".
- name: Set cpu flags fact
  set_fact:
    cpu_flags: "{{ cpu_flags_cmd.stdout.split() }}"

- block:
    - name: Unload kvm_intel module
      modprobe:
        name: "kvm_intel"
        state: "absent"

    - name: Re-load KVM module with Intel nested virtualization support
      modprobe:
        name: "kvm_intel"
        state: "present"
        params: "nested=1"
      register: nested_virtualization
  when:
    - "{{ 'Intel' in ansible_processor |join('') }}"
    - "{{ 'vmx' in cpu_flags }}"

- block:
    - name: Unload kvm_amd module
      modprobe:
        name: "kvm_amd"
        state: "absent"

    - name: Re-load KVM module with AMD nested virtualization support
      modprobe:
        name: "kvm_amd"
        state: "present"
        params: "nested=1"
      register: nested_virtualization
  when:
    - "{{ 'AMD' in ansible_processor |join('') }}"
    - "{{ 'svm' in cpu_flags }}"
