---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

# Note: Handlers are grouped here to be ordered properly, see
# http://docs.ansible.com/ansible/glossary.html#notify

# These handlers are used from other roles and thus the path needs to be
# specified to go back to the roles dir (from the role calling handler)
# Doing inter-role includes is a bit wonky.
# See: https://github.com/ansible/ansible/issues/13818
- name: Ensure global logs are recovered
  include: ../../common/tasks/logs.yml

- name: Fail playbook execution
  fail:
    msg: "A task notified that the playbook execution should be failed"
